### PR TITLE
Android updates (gradle, build)

### PR DESCRIPTION
**Pull request by ened**
V0.0.5: Various Android updates

### CODE REVIEW

**Comment by ened** [comment]
@ened ready for your review

**Comment by Aragur** [comment]
Would be nice if this would be merged soon :)
Builds are failing atm because build tools 25.3.3 got removed from the maven repositories...
```
> Could not resolve all artifacts for configuration ':screen:classpath'.
   > Could not find com.android.tools:common:25.3.3.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/android/tools/common/25.3.3/common-25.3.3.pom
       - https://jcenter.bintray.com/com/android/tools/common/25.3.3/common-25.3.3.jar
       - https://maven.google.com/com/android/tools/common/25.3.3/common-25.3.3.pom
       - https://maven.google.com/com/android/tools/common/25.3.3/common-25.3.3.jar
```

**Comment by arranf** [comment]
@clovisnicolas I think you were meant to be @'ed above!

**Comment by ened** [comment]
For anyone interested, you can use my branch directly by adjusting your pubspec.yaml:

```
  screen:
    git:
      url: https://github.com/ened/flutter_screen.git
      ref: android-cleanup
```

**Comment by ened** [comment]
@clovisnicolas ready to merge & publish?

**Comment by clovisnicolas** [comment]
Hello, done, sorry for the delay

**Pull request merged**
